# docker compose up

version: "3.1"

services:
  app:
    build: .
    container_name: ottai-nightscout-uploader
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      OTTAI_BASE_URL:
      OTTAI_TOKEN: 
      NS_URL:
      NS_API_SECRET:
      HOURS_AGO:
    command: python -u main.py